#pragma once

#include "Windows.h"

namespace sia
{
    namespace windows_tag
    {
        namespace window_message
        {
            enum : UINT
            {
                null = WM_NULL,
                create = WM_CREATE,
                destroy = WM_DESTROY,
                move = WM_MOVE,
                size = WM_SIZE,
                activate = WM_ACTIVATE,
                set_focus = WM_SETFOCUS,
                kill_focus = WM_KILLFOCUS,
                enable = WM_ENABLE,
                set_redrew= WM_SETREDRAW,
                set_text = WM_SETTEXT,
                get_text = WM_GETTEXT,
                get_text_length = WM_GETTEXTLENGTH,
                paint = WM_PAINT,
                close = WM_CLOSE,
                query_end_session= WM_QUERYENDSESSION,
                query_open = WM_QUERYOPEN,
                end_session = WM_ENDSESSION,
                quit = WM_QUIT,
                erase_bg = WM_ERASEBKGND,
                sys_color_chage = WM_SYSCOLORCHANGE,
                show_window = WM_SHOWWINDOW,
                win_ini_chage = WM_WININICHANGE,
                setting_change = WM_WININICHANGE,
                dev_mode_change= WM_DEVMODECHANGE,
                activate_app = WM_ACTIVATEAPP,
                font_change = WM_FONTCHANGE,
                time_change = WM_TIMECHANGE,
                cancel_mode = WM_CANCELMODE,
                set_cursor = WM_SETCURSOR,
                mouse_activate = WM_MOUSEACTIVATE,
                child_activate = WM_CHILDACTIVATE,
                queue_sync = WM_QUEUESYNC,
                get_min_max_info = WM_GETMINMAXINFO,
                paint_icon = WM_PAINTICON,
                icon_erase_bg = WM_ICONERASEBKGND,
                next_dlg_ctl = WM_NEXTDLGCTL,
                spooler_status = WM_SPOOLERSTATUS,
                draw_item = WM_DRAWITEM,
                measure_item = WM_MEASUREITEM,
                delete_item = WM_DELETEITEM,
                vkey_to_item = WM_VKEYTOITEM,
                char_to_item = WM_CHARTOITEM,
                set_font = WM_SETFONT,
                get_font = WM_GETFONT,
                set_hotkey = WM_SETHOTKEY,
                get_hotkey = WM_GETHOTKEY,
                query_drag_icon = WM_QUERYDRAGICON,
                compare_item = WM_COMPAREITEM,
                get_object = WM_GETOBJECT,
                compaction = WM_COMPACTING,
                window_pos_changing = WM_WINDOWPOSCHANGING,
                window_pos_changed = WM_WINDOWPOSCHANGED,
                power = WM_POWER,
                copy_data = WM_COPYDATA,
                cancel_journal = WM_CANCELJOURNAL,
                notify = WM_NOTIFY,
                input_language_change_request = WM_INPUTLANGCHANGEREQUEST,
                input_language_change = WM_INPUTLANGCHANGE,
                tcard = WM_TCARD,
                help = WM_HELP,
                user_changed = WM_USERCHANGED,
                notify_format = WM_NOTIFYFORMAT,
                context_menu = WM_CONTEXTMENU,
                style_changing = WM_STYLECHANGING,
                style_changed = WM_STYLECHANGED,
                display_change = WM_DISPLAYCHANGE,
                get_icon = WM_GETICON,
                set_icon = WM_SETICON,
                nc_create = WM_NCCREATE,
                nc_destroy = WM_NCDESTROY,
                nc_calc_size = WM_NCCALCSIZE,
                nc_hit_test = WM_NCHITTEST,
                nc_paint = WM_NCPAINT,
                nc_activate = WM_NCACTIVATE,
                get_dlg_code = WM_GETDLGCODE,
                sync_paint = WM_SYNCPAINT,
                nc_mouse_move = WM_NCMOUSEMOVE,
                nc_l_button_down = WM_NCLBUTTONDOWN,
                nc_l_button_up = WM_NCLBUTTONUP,
                nc_l_button_click = WM_NCLBUTTONDBLCLK,
                nc_r_button_down = WM_NCRBUTTONDOWN,
                nc_r_button_up = WM_NCRBUTTONUP,
                nc_r_button_click = WM_NCRBUTTONDBLCLK,
                nc_m_button_down = WM_NCMBUTTONDOWN,
                nc_m_button_up = WM_NCMBUTTONUP,
                nc_m_button_click = WM_NCMBUTTONDBLCLK,
                nc_x_button_down = WM_NCXBUTTONDOWN,
                nc_x_button_up = WM_NCXBUTTONUP,
                nc_x_button_click = WM_NCXBUTTONDBLCLK,
                input_device_chage = WM_INPUT_DEVICE_CHANGE,
                input = WM_INPUT,
                key_first = WM_KEYFIRST,
                key_down = WM_KEYDOWN,
                key_up = WM_KEYUP,
                chracter = WM_CHAR,
                dead_char= WM_DEADCHAR,
                sys_key_down = WM_SYSKEYDOWN,
                sys_key_up = WM_SYSKEYUP,
                sys_key_char = WM_SYSCHAR,
                sys_dead_char = WM_SYSDEADCHAR,
                uni_char = WM_UNICHAR,
                key_last = WM_KEYLAST,
                ime_start_composition = WM_IME_STARTCOMPOSITION,
                ime_end_composition = WM_IME_ENDCOMPOSITION,
                ime_composition = WM_IME_COMPOSITION,
                ime_key_last = WM_IME_KEYLAST,
                init_dialog = WM_INITDIALOG,
                command = WM_COMMAND,
                sys_command = WM_SYSCOMMAND,
                timer = WM_TIMER,
                h_scroll = WM_HSCROLL,
                v_scroll = WM_VSCROLL,
                init_menu = WM_INITMENU,
                init_menu_popup= WM_INITMENUPOPUP,
                get_true = WM_GESTURE,
                get_true_notify = WM_GESTURENOTIFY,
                menu_select = WM_MENUSELECT,
                menu_char = WM_MENUCHAR,
                enter_idle = WM_ENTERIDLE,
                menu_r_button_up= WM_MENURBUTTONUP,
                menu_drag = WM_MENUDRAG,
                menu_get_object = WM_MENUGETOBJECT,
                uninit_menu_popup = WM_UNINITMENUPOPUP,
                menu_command = WM_MENUCOMMAND,
                change_ui_state = WM_CHANGEUISTATE,
                update_ui_state = WM_UPDATEUISTATE,
                query_ui_state = WM_QUERYUISTATE,
                ctl_color_msgbox = WM_CTLCOLORMSGBOX,
                ctl_color_edit = WM_CTLCOLOREDIT,
                ctl_color_listbox = WM_CTLCOLORLISTBOX,
                ctl_color_btn = WM_CTLCOLORBTN,
                ctl_color_dlg = WM_CTLCOLORDLG,
                ctl_color_scrollbar = WM_CTLCOLORSCROLLBAR,
                ctl_color_static = WM_CTLCOLORSTATIC,
                mouse_first = WM_MOUSEFIRST,
                mouse_move = WM_MOUSEMOVE,
                l_button_down = WM_LBUTTONDOWN,
                l_button_up = WM_LBUTTONUP,
                l_button_click = WM_LBUTTONDBLCLK,
                r_button_down = WM_RBUTTONDOWN,
                r_button_up = WM_RBUTTONUP,
                r_button_click = WM_RBUTTONDBLCLK,
                m_button_down = WM_MBUTTONDOWN,
                m_button_up = WM_MBUTTONUP,
                m_button_click = WM_MBUTTONDBLCLK,
                mouse_wheel = WM_MOUSEWHEEL,
                x_button_down = WM_XBUTTONDOWN,
                x_button_up = WM_XBUTTONUP,
                x_button_click = WM_XBUTTONDBLCLK,
                mouse_last = WM_MOUSELAST,
                parent_nofify = WM_PARENTNOTIFY,
                enter_menu_loop = WM_ENTERMENULOOP,
                exit_menu_loop = WM_EXITMENULOOP,
                next_menu = WM_NEXTMENU,
                sizeing = WM_SIZING,
                capture_change = WM_CAPTURECHANGED,
                moving = WM_MOVING,
                power_broadcast = WM_POWERBROADCAST,
                device_chage = WM_DEVICECHANGE,
                mdi_create = WM_MDICREATE,
                mdi_destroy = WM_MDIDESTROY,
                mid_activate = WM_MDIACTIVATE,
                mdi_restore = WM_MDIRESTORE,
                mdi_next = WM_MDINEXT,
                mdi_maximize = WM_MDIMAXIMIZE,
                mdi_tile = WM_MDITILE,
                mdi_cascade = WM_MDICASCADE,
                mdi_icon_arrange = WM_MDIICONARRANGE,
                mdi_get_active = WM_MDIGETACTIVE,
                mdi_set_menu = WM_MDISETMENU,
                enter_size_move = WM_ENTERSIZEMOVE,
                exit_size_move = WM_EXITSIZEMOVE,
                drop_files = WM_DROPFILES,
                mdi_refresh_menu = WM_MDIREFRESHMENU,
                pointer_device_change = WM_POINTERDEVICECHANGE,
                pointer_device_in_range = WM_POINTERDEVICEINRANGE,
                pointer_device_out_range= WM_POINTERDEVICEOUTOFRANGE,
                touch = WM_TOUCH,
                nc_pointer_update = WM_NCPOINTERUPDATE,
                nc_pointer_down = WM_NCPOINTERDOWN,
                nc_pointer_up = WM_NCPOINTERUP,
                pointer_update = WM_POINTERUPDATE,
                pointer_down = WM_POINTERDOWN,
                pointer_up = WM_POINTERUP,
                pointer_enter = WM_POINTERENTER,
                pointer_leave = WM_POINTERLEAVE,
                pointer_activate = WM_POINTERACTIVATE,
                pointer_capture_changed = WM_POINTERCAPTURECHANGED,
                touch_hit_testing = WM_TOUCHHITTESTING,
                pointer_wheel = WM_POINTERWHEEL,
                pointer_h_wheel = WM_POINTERHWHEEL,
                pointer_routed_to = WM_POINTERROUTEDTO,
                pointer_routed_away = WM_POINTERROUTEDAWAY,
                pointer_routed_release = WM_POINTERROUTEDRELEASED,
                ime_set_context = WM_IME_SETCONTEXT,
                ime_notify = WM_IME_NOTIFY,
                ime_control = WM_IME_CONTROL,
                ime_conposition_full = WM_IME_COMPOSITIONFULL,
                ime_select = WM_IME_SELECT,
                ime_char = WM_IME_CHAR,
                ime_request = WM_IME_REQUEST,
                ime_key_down = WM_IME_KEYDOWN,
                ime_key_up = WM_IME_KEYUP,
                mouse_hover = WM_MOUSEHOVER,
                mouse_leave = WM_MOUSELEAVE,
                nc_mouse_hover = WM_NCMOUSEHOVER,
                nc_mouse_leave = WM_NCMOUSELEAVE,
                wts_sesstion_chage = WM_WTSSESSION_CHANGE,
                tablet_first = WM_TABLET_FIRST,
                table_last = WM_TABLET_LAST,
                dpi_chaged = WM_DPICHANGED,
                dpi_changed_before_parent = WM_DPICHANGED_BEFOREPARENT,
                dpi_changed_after_parent = WM_DPICHANGED_AFTERPARENT,
                get_dpi_scaled_size = WM_GETDPISCALEDSIZE,
                cut = WM_CUT,
                copy = WM_COPY,
                paste = WM_PASTE,
                clear = WM_CLEAR,
                undo = WM_UNDO,
                render_format = WM_RENDERFORMAT,
                render_all_formats = WM_RENDERALLFORMATS,
                destroy_clip_board = WM_DESTROYCLIPBOARD,
                draw_clip_board = WM_DRAWCLIPBOARD,
                paint_clip_board = WM_PAINTCLIPBOARD,
                v_scroll_clip_board = WM_VSCROLLCLIPBOARD,
                size_clipboard = WM_SIZECLIPBOARD,
                ask_cb_format_name = WM_ASKCBFORMATNAME,
                change_cb_chain = WM_CHANGECBCHAIN,
                h_scroll_clipboard = WM_HSCROLLCLIPBOARD,
                query_new_palette = WM_QUERYNEWPALETTE,
                palette_is_changing = WM_PALETTEISCHANGING,
                palette_chaged = WM_PALETTECHANGED,
                hot_key = WM_HOTKEY,
                print = WM_PRINT,
                print_client = WM_PRINTCLIENT,
                app_command = WM_APPCOMMAND,
                theme_chaged = WM_THEMECHANGED,
                clipboard_update = WM_CLIPBOARDUPDATE,
                swm_composition_changed = WM_DWMCOMPOSITIONCHANGED,
                dwm_nc_rendering_changed= WM_DWMNCRENDERINGCHANGED,
                dwm_colorization_color_changed = WM_DWMCOLORIZATIONCOLORCHANGED,
                dwm_window_maximized_change = WM_DWMWINDOWMAXIMIZEDCHANGE,
                dwm_send_iconic_thumbnail = WM_DWMSENDICONICTHUMBNAIL,
                dwm_send_iconic_live_preview_bitmap = WM_DWMSENDICONICLIVEPREVIEWBITMAP,
                get_title_bar_info_ex = WM_GETTITLEBARINFOEX,
                hand_held_first = WM_HANDHELDFIRST,
                hand_held_last = WM_HANDHELDLAST,
                afx_first = WM_AFXFIRST,
                afx_last = WM_AFXLAST,
                pen_win_first = WM_PENWINFIRST,
                pen_win_last = WM_PENWINLAST,
                app = WM_APP,
                user = WM_USER,
                tooltip_dismiss= WM_TOOLTIPDISMISS
            };
        } // namespace window_message
        
        namespace show_window
        {
            // https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-showwindow
            enum : int
            {
                hide            = SW_HIDE,
                normal          = SW_NORMAL,
                minimized       = SW_MINIMIZE,
                maximized       = SW_MAXIMIZE,
                noactivate      = SW_SHOWNOACTIVATE,
                show            = SW_SHOW,
                min_noactivate  = SW_SHOWMINNOACTIVE,
                show_na         = SW_SHOWNA,
                restore         = SW_RESTORE,
                show_default    = SW_SHOWDEFAULT,
                force_minimize  = SW_FORCEMINIMIZE
            };
        } // namespace show_window
        
        namespace window_class_style
        {
            // https://learn.microsoft.com/en-us/windows/win32/winmsg/window-class-styles
            enum : DWORD
            {
                byte_align_client    = CS_BYTEALIGNCLIENT,
                byte_align_window    = CS_BYTEALIGNWINDOW,
                class_dc             = CS_CLASSDC,
                dblclks              = CS_DBLCLKS,
                drop_shadow          = CS_DROPSHADOW,
                global_class         = CS_GLOBALCLASS,
                h_redraw             = CS_HREDRAW,
                v_redraw             = CS_VREDRAW,
                no_close             = CS_NOCLOSE,
                own_dc               = CS_OWNDC,
                parent_dc            = CS_PARENTDC,
                save_bits            = CS_SAVEBITS
            };
        } // namespace window_class_style
        
        namespace window_style
        {
            // https://learn.microsoft.com/en-us/windows/win32/winmsg/window-styles
            enum : DWORD
            {
                boarder                 = WS_BORDER,
                caption                 = WS_CAPTION,
                child                   = WS_CHILD,
                child_window            = WS_CHILDWINDOW,
                clip_children           = WS_CLIPCHILDREN,
                clip_sublings           = WS_CLIPSIBLINGS,
                disabled                = WS_DISABLED,
                dlg_frame               = WS_DLGFRAME,
                group                   = WS_GROUP,
                h_scroll                = WS_HSCROLL,
                iconic                  = WS_ICONIC,
                maximize                = WS_MAXIMIZE,
                maximize_box            = WS_MAXIMIZEBOX,
                minimize                = WS_MINIMIZE,
                minimize_box            = WS_MINIMIZEBOX,
                overlapped              = WS_OVERLAPPED,
                overlapped_window       = WS_OVERLAPPEDWINDOW,
                popup                   = WS_POPUP,
                popup_window            = WS_POPUPWINDOW,
                sizebox                 = WS_SIZEBOX,
                sysmenu                 = WS_SYSMENU,
                tabstop                 = WS_TABSTOP,
                thick_frame             = WS_THICKFRAME,
                tiled                   = WS_TILED,
                tiled_window            = WS_TILEDWINDOW,
                visible                 = WS_VISIBLE,
                v_scroll                = WS_VSCROLL
            };
        } // namespace window_style

        namespace window_style_ex
        {
            // https://learn.microsoft.com/en-us/windows/win32/winmsg/extended-window-styles
            enum : DWORD
            {
                accept_files            = WS_EX_ACCEPTFILES,
                app_window              = WS_EX_APPWINDOW,
                client_edge             = WS_EX_CLIENTEDGE,
                composited              = WS_EX_COMPOSITED,
                context_help            = WS_EX_CONTEXTHELP,
                control_parent          = WS_EX_CONTROLPARENT,
                dlg_modal_frame         = WS_EX_DLGMODALFRAME,
                layered                 = WS_EX_LAYERED,
                layout_rtl              = WS_EX_LAYOUTRTL,
                left                    = WS_EX_LEFT,
                left_scrollbar          = WS_EX_LEFTSCROLLBAR,
                ltr_reading             = WS_EX_LTRREADING,
                mdi_child               = WS_EX_MDICHILD,
                noactivate              = WS_EX_NOACTIVATE,
                no_ingerit_layout       = WS_EX_NOINHERITLAYOUT,
                no_parent_notify        = WS_EX_NOPARENTNOTIFY,
                no_redirection_bitmap   = WS_EX_NOREDIRECTIONBITMAP,
                overlapped_window_ex    = WS_EX_OVERLAPPEDWINDOW,
                palette_window          = WS_EX_PALETTEWINDOW,
                right                   = WS_EX_RIGHT,
                right_sctollbar         = WS_EX_RIGHTSCROLLBAR,
                rtl_reading             = WS_EX_RTLREADING,
                static_edge             = WS_EX_STATICEDGE,
                tool_window             = WS_EX_TOOLWINDOW,
                top_most                = WS_EX_TOPMOST,
                window_edge             = WS_EX_WINDOWEDGE
            };
        } // namespace window_style_ex
    } // namespace windows_tag
} // namespace sia
